language: python
python:
  - "3.6"
os:
  - linux
  # - osx  # not supported yet
install:
  - pip install -U pip setuptools
  - pip install -U -r requirements-ci.txt
script:
  - pytest -m "not integration"
